### PR TITLE
fix lengths of ticks/labels

### PR DESCRIPTION
**Pull request by nllong**

### CODE REVIEW

**Comment by ThibaultMarzullo** [comment]
I suggest changing lines 94 and 95 to:
```
xticks = range(0, int(mp.length) + 6 * 3600, int(6 * 3600))
xlabels = range(0, int(mp.length/3600) + 6, 6)
```
Now, the ticks have the correct length (which strangely did not raise an error on my end) and the 24-hour tick also appears. It stopped at 18 before.

**Review by ThibaultMarzullo — CHANGES_REQUESTED** [review]
This [comment](https://github.com/henze-research-group/MODRLC/pull/23#issuecomment-985188178) proposes a solution for getting rid of the error and also showing the correct ticks.

**Comment by nllong** [comment]
> This [comment](https://github.com/henze-research-group/MODRLC/pull/23#issuecomment-985188178) proposes a solution for getting rid of the error and also showing the correct ticks.

good point, look better @ThibaultMarzullo ?

**Review by ThibaultMarzullo — APPROVED** [review]
Looks good!

**Pull request merged**
