### PR TITLE
Metamodeling framework, Spawn data generator, reset function

### PR DESCRIPTION
**Pull request by ThibaultMarzullo**
This PR includes:
- the new Spawn data extraction utility found in `spawn-tools`. It generates files for the Spawn FMU, later used by BOPTEST for forecasts and KPIs. The data is extracted from the epw and idf files used in the Spawn model. 
- the new metamodeling framework. This new version will run Spawn and collect model data, then identify a state-space model using N4SID. Implements best subset selection and forward step-wise selection. All the matrices are then saved where the MPC can find them.
- a new reset function for the ACTB client, and helper functions
- MPC (non-DR) example update: changed the TVP sources and minor cleanup
- RBC (non-DR) update with the new stop() function
- repo cleanup, all Spawn resources now go to `testcases\SpawnResources\<testcase name>`. This includes Spawn data to be included in FMUs, metamodels, etc.

### CODE REVIEW

**Comment by ThibaultMarzullo** [comment]
It looks like there is a conflict due to the tick labels in the MPC example. I did not pull that commit before doing the changes. Can we resolve this without undoing all the changes I made in the new commit?

**Review by nllong — APPROVED** [review]
These changes look great. I didn't go through them 1-by-1, but they worked as expected on my computer.

**Comment by nllong** [comment]
@ThibaultMarzullo  -- you'll need to resolve the conflicts before merging...

**Comment by ThibaultMarzullo** [comment]
Thanks Nick, it has to do with the MPC plot ticks, I'll fix that.

**Pull request merged**
