### PR TITLE
Rl gym functionalities for plotting and saving added 

### PR DESCRIPTION
**Pull request by SouravDaedo**
Hi, 

I added some functionalities to the gym interface, like automatically saving the data and plotting the graphs. Can you review and add it to the main branch.

### CODE REVIEW

**Comment by ThibaultMarzullo** [comment]
@SouravDaedo you have committed a lot of changes that come from other files in other branches, such as the ones to the actb_client, metamodeling framework, MPC simulator file, etc.
This will create conflicts once we merge other branches like the dr-examples, the metamodels, and the multibuilding branch.
Please revise this PR, or better, create a new branch from the branch that contains the files that I listed above, add your changes, commit them, and merge in that other branch. That other branch will then need a new PR because it is likely not ready to be merged in the main branch. If I recall correctly, you are using files from the multibuilding branch, right?

**Comment by SouravDaedo** [comment]
Yes I maybe using files from other as rl-gym might have been branched out from dr_examples branch . Would branching out from the existing main branch and adding my files help in creating a better PR ?

**Comment by ThibaultMarzullo** [comment]
Absolutely, so long as you only use the files you updated. If the files that I mentioned in my first comment are not on the main branch, search for them in the other branches (I believe you will find them in the multibuilding branch) and fork from that branch. We can merge these branches together, and I will finish the work on the multibuilding branch and merge it back to the main one ASAP so that we can issue a new patch to 0.2 with all your work. We might even make it a 0.3 since there are substantial changes.
On a side note, you can ignore the `jobs.json` file and un-track it as it is generated by the user anyway.

**Comment by SouravDaedo** [comment]
Cool ! Thanks !

**Pull request closed without merging**
